---
title: "Overdispersion test"
author: "Reijo Leinonen"
date: "2023-08-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
library(dplyr)
library(sf)
setwd("C:/Users/reijo/OneDrive/Documents/Thesis/R")
data <- readRDS("C:/Users/reijo/Desktop/yliopisto/master_thesis/moose_forest_damages/data/Data_Frames/data.rds")
# rename abbreviated column names
colnames(data) <-  c("ID", "DAMAGE", "OPENMIN", "OPENPEAT", "PINEPLAMIN", "PINEPLAPEATND", "PINEPLAPEATDR", "OTHERPLANT", "PINETHIMIN", "PINETHIPEATND", "PINETHIPEATDR", "OTHERTHI", "MATURE", "WATER", "INHABITED", "AGRI", "MANMADE", "MAINROAD", "REGROAD", "CONNROAD", "FORROAD", "OTHERROAD", "DENSITY", "LON", "LAT", "AREA", "geometry")
#remove geometry column
data <- data %>% st_drop_geometry()
pois_mod <- glm(DAMAGE~., data = data, family = poisson(link = "log"))
AER::dispersiontest(pois_mod, trafo=1)

library(MASS)
nb_mod <- glm.nb(DAMAGE ~ ., data = data)


#Residual plot for Poisson regression
p_res <- resid(pois_mod)
plot(fitted(pois_mod), p_res, col='steelblue', pch=16,
     xlab='Predicted Offers', ylab='Standardized Residuals', main='Poisson')
abline(0,0)

#Residual plot for negative binomial regression 
nb_res <- resid(nb_mod)
plot(fitted(nb_mod), nb_res, col='steelblue', pch=16,
     xlab='Predicted Offers', ylab='Standardized Residuals', main='Negative Binomial')
abline(0,0)

#plot(fitted(rd), res)
#
## add a horizontal line at 0 
#abline(0,0)

```
